#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$opts = getopt("b:");
$birthDate = $opts["b"] ?? "1978-04-09";
$days = new \Evdokimov\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays() ;

echo "$birthDate : $totalDays\n";
