#!/usr/bin/env php
<?php
$opts = getopt("b:");

$birthDate = $opts["b"]??"1978-04-09";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);

echo "$birthDate : $totalDays\n";
